# https://hub.docker.com/r/bitnami/kafka/
# refer to Section:  (Kafka development setup example)
version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

# Helpful commands
# docker-compose up -d
# kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
# kafka-topics --list --zookeeper localhost:2181
# kafka-topics --list --bootstrap-server localhost:9092
